"""Structural ports shared by local and hosted bridge adapters."""

from __future__ import annotations

from typing import Any, Protocol


class ActionQueuePort(Protocol):
    def create(self, **values: Any) -> tuple[dict[str, Any], bool]: ...
    def list(self, *, target_device_id: str = "", limit: int = 100) -> list[dict[str, Any]]: ...
    def get(self, action_id: str) -> dict[str, Any] | None: ...
    def claim_next(self, target_device_id: str) -> dict[str, Any] | None: ...
    def acknowledge(
        self,
        target_device_id: str,
        action_id: str,
        status: str,
        error: str = "",
        result: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...


class ConversationStorePort(Protocol):
    def active_session(self) -> dict[str, Any] | None: ...
    def create_session(self) -> dict[str, Any]: ...
    def session_expired(self, session: dict[str, Any]) -> bool: ...
    def history(self, session_id: str, limit: int) -> list[dict[str, str]]: ...
    def turns(self, session_id: str) -> list[dict[str, Any]]: ...
    def append(self, session_id: str, device_id: str, role: str, content: str, **values: Any) -> Any: ...
    def append_exchange(self, session_id: str, *values: Any, **metadata: Any) -> Any: ...
    def end_session(self, session: dict[str, Any]) -> Any: ...
    def archive(self, session: dict[str, Any], summary: str | None = None) -> int: ...
    def clear(self) -> int: ...
    def list_sessions(self, limit: int = 20) -> list[dict[str, Any]]: ...
    def rename(self, session_id: str, title: str) -> dict[str, Any]: ...
    def list_device_ids(self, session_id: str | None = None) -> list[str]: ...


class DurableMemoryPort(Protocol):
    def retrieve(self, query: str, limit: int) -> list[str]: ...
    def add(self, content: str) -> bool: ...
