create table if not exists public.wearabllm_conversation_sessions (
    id uuid primary key default gen_random_uuid(),
    principal_id text not null check (char_length(principal_id) between 1 and 80),
    started_at timestamptz not null default now(),
    last_turn_at timestamptz not null default now(),
    ended_at timestamptz,
    archived_at timestamptz,
    summary text check (summary is null or char_length(summary) <= 12000)
);

create unique index if not exists wearabllm_one_active_session_per_principal_idx
    on public.wearabllm_conversation_sessions (principal_id)
    where ended_at is null;

alter table public.wearabllm_conversation_sessions enable row level security;
revoke all on table public.wearabllm_conversation_sessions from anon, authenticated;
grant select, insert, update, delete on table public.wearabllm_conversation_sessions to service_role;

alter table public.wearabllm_conversation_turns
    add column if not exists session_id uuid references public.wearabllm_conversation_sessions (id);

alter table public.wearabllm_conversation_turns
    alter column session_id set not null;

create index if not exists wearabllm_conversation_turns_session_created_idx
    on public.wearabllm_conversation_turns (session_id, created_at desc, id desc);

create table if not exists public.wearabllm_conversation_archive (
    id bigint generated by default as identity primary key,
    archived_at timestamptz not null default now(),
    original_turn_id bigint not null unique,
    session_id uuid not null references public.wearabllm_conversation_sessions (id),
    principal_id text not null check (char_length(principal_id) between 1 and 80),
    device_id text not null check (device_id ~ '^[A-Za-z0-9._-]{1,80}$'),
    role text not null check (role in ('user', 'assistant')),
    content text not null check (char_length(content) between 1 and 4000),
    created_at timestamptz not null
);

create index if not exists wearabllm_conversation_archive_principal_created_idx
    on public.wearabllm_conversation_archive (principal_id, created_at desc, id desc);

alter table public.wearabllm_conversation_archive enable row level security;
revoke all on table public.wearabllm_conversation_archive from anon, authenticated;
grant select, insert, delete on table public.wearabllm_conversation_archive to service_role;
grant usage, select on sequence public.wearabllm_conversation_archive_id_seq to service_role;

comment on table public.wearabllm_conversation_sessions is
    'Private one-hour-or-configured active conversation sessions, with optional consolidation summaries.';
comment on table public.wearabllm_conversation_archive is
    'Private indefinite raw WearabLLM transcript archive. Archived turns are never prompt context by default.';
