create table if not exists public.device_transcripts (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    device_id text not null check (char_length(device_id) between 1 and 80),
    interaction_id bigint not null check (interaction_id >= 0),
    command text not null check (command in ('GS', 'GP', 'GC', 'RS', 'RF', 'YP', 'BS', 'PS', 'PP')),
    transcript text not null check (char_length(transcript) between 1 and 2000),
    reply text not null default '' check (char_length(reply) <= 4000),
    capture_source text not null default 'unknown' check (char_length(capture_source) <= 40)
);

create index if not exists device_transcripts_created_at_idx
    on public.device_transcripts (created_at desc);

alter table public.device_transcripts enable row level security;

revoke all on table public.device_transcripts from anon, authenticated;
grant select, insert, delete on table public.device_transcripts to service_role;
grant usage, select on sequence public.device_transcripts_id_seq to service_role;

comment on table public.device_transcripts is
    'Private WearabLLM device transcripts. No anon or authenticated API policies.';
