create table if not exists public.wearabllm_conversation_turns (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    principal_id text not null check (char_length(principal_id) between 1 and 80),
    device_id text not null check (device_id ~ '^[A-Za-z0-9._-]{1,80}$'),
    role text not null check (role in ('user', 'assistant')),
    content text not null check (char_length(content) between 1 and 4000)
);

create index if not exists wearabllm_conversation_turns_principal_created_idx
    on public.wearabllm_conversation_turns (principal_id, created_at desc);

alter table public.wearabllm_conversation_turns enable row level security;

revoke all on table public.wearabllm_conversation_turns from anon, authenticated;
grant select, insert, delete on table public.wearabllm_conversation_turns to service_role;
grant usage, select on sequence public.wearabllm_conversation_turns_id_seq to service_role;

comment on table public.wearabllm_conversation_turns is
    'Private bounded recent conversation shared by WearabLLM device bodies. The hosted bridge accesses it only with the server-side service role.';
